name: patapata_adjust_deeplink
description: This package is a plugin for Patapata that adds support for Adjust deep link to your Patapata app.
version: 1.0.0
homepage: https://github.com/gree/patapata
repository: https://github.com/gree/patapata/tree/main/packages/patapata_adjust_deeplink

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

  patapata_core: ^1.4.0
  app_links: ^6.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  plugin:
    platforms:
      android:
        package: dev.patapata.patapata_adjust_deeplink
        pluginClass: PatapataAdjustDeeplinkPlugin
      ios:
        pluginClass: PatapataAdjustDeeplinkPlugin
